### ISSUE TITLE
It will be much nicer if an empty "username" field will act as a "default" user

### ISSUE THREAD

**Issue by alexey-milovidov** [datalens-tech/datalens#10]
![Screenshot_20230926_185118](https://github.com/datalens-tech/datalens/assets/18581488/1fd8bf9b-c1c0-47be-b9bc-910792f4679f)

**Comment by resure** [comment]
It should already work like that, we'll look into it.

**Comment by KonstantAnxiety** [comment]
Hi @alexey-milovidov 
This behaviour should've been updated after https://github.com/datalens-tech/datalens-backend/pull/164
Please, try this on the latest [DataLens](https://github.com/datalens-tech/datalens) version and tell if the connector is working as expected now
