### ISSUE TITLE
Add background option for Text Element

### ISSUE THREAD

**Issue by skaradub** [datalens-tech/datalens#104]
Hello there!

As for now it is only possible to add background via info object (red, yellow, green) and all other elements have no background at all. If we use Text element as Header - ok, But if we want to make some information block we can't devide information pretty. It would be great to have "show background" checkbox to solve this problem
![2texts_no_separation](https://github.com/datalens-tech/datalens/assets/57046561/b57e1b22-292b-4a56-8903-f823db0cb2ca)

Regards, 
Yury

**Comment by Marginy605** [comment]
@skaradub We are glad to inform you that we've implemented background option for Text and Title Widget. It would be available on recent version of containers images. 
Also we are going to improve this feature by adding same as chart widget background
