### ISSUE TITLE
demo data for docker-compose.yml as an option

### ISSUE THREAD

**Issue by andyshapirov** [datalens-tech/datalens#117]
hey there!

pls add the option to disable the loading of demo data in docker-compose.yml, considering that the prod-version is primarily not for testing or entertainment

p.s.: the existing method of manually deleting demo data is not the best practice

ty

**Comment by imsitnikov** [comment]
@andyshapirov Hi! You can add env variable `USE_DEMO_DATA=0` when running `docker compose up` and demo data shouldn't appear.

**Comment by andyshapirov** [comment]
Hi! ty!

вт, 19 мар. 2024 г., 14:09 Maksim Sitnikov ***@***.***>:
