### ISSUE TITLE
It takes more than five minutes to understand how to add metrics to a chart

### ISSUE THREAD

**Issue by alexey-milovidov** [datalens-tech/datalens#13]
![Screenshot_20230926_191020](https://github.com/datalens-tech/datalens/assets/18581488/19caa5e5-b4e3-4987-9600-b4757a2bf37d)

Currently, I haven't succeeded yet, will try later.

**Comment by Konstantin-Roumas** [comment]
Can you descibe your steps?

**Comment by paveldubinin** [comment]
There are two ways you can create calculated fields:
1) on dataset level (could be used in any charts on this dataset) 
![image](https://github.com/datalens-tech/datalens/assets/7340915/923d8d5e-61c3-498b-b993-0f7c21531f70)

2) on chart level (field will be available only in the current chart)
![image](https://github.com/datalens-tech/datalens/assets/7340915/d1541673-a6a0-4735-b1d6-c28c5c44cff2)

More details about calculated fields you can find [here in documentation](https://datalens.tech/docs/en/concepts/calculations/).And [here](https://datalens.tech/docs/en/function-ref/all.html) is reference for the supported functions.

To add calculated field to the chart simply drag it to the corresponding section:
![image](https://github.com/datalens-tech/datalens/assets/7340915/e9e96c48-7f65-43a2-9cc3-df157276b1a1)
Details about [chart creation](https://datalens.tech/docs/en/concepts/chart/dataset-based-charts.html)
