### ISSUE TITLE
I am loosing all my preferences after restarted docker container

### ISSUE THREAD

**Issue by nutritiouss** [datalens-tech/datalens#18]
After executing command -  ``` docker compose down&&docker compose up -d``` I am loosing all my settings. I tried to attach volumes to containers ``` pg-compeng, pg-us``` like this:
 
```bash
   volumes:
        - pg-compeng:/var/lib/postgresql/data
    volumes:
        - pg-us:/var/lib/postgresql/data
 volumes:
  pg-compeng:
  pg-us:       
 ```

Can anyone help me make the docker-compose file resistant to reboots?

**Comment by melikhov-dev** [comment]
> Can anyone help me make the docker-compose file resistant to reboots?

Hi, @nutritiouss! Unfortunately, this is a more complex problem than simply mounting volumes. We recreate the demo DB after each restart of `us` container, but we will fix this behavior immediately.

**Comment by shushlyakov** [comment]
> After executing command - ` docker compose down&&docker compose up -d` I am loosing all my settings. I tried to attach volumes to containers ` pg-compeng, pg-us` like this:
> 
> ```shell
>    volumes:
>         - pg-compeng:/var/lib/postgresql/data
>     volumes:
>         - pg-us:/var/lib/postgresql/data
>  volumes:
>   pg-compeng:
>   pg-us:       
> ```
> 
> Can anyone help me make the docker-compose file resistant to reboots?

Run for the first time with the parameters
```shell
PG_TEST_DATA: 1
CH_DEMO_DATA: 1
```
after
```shell
PG_TEST_DATA: 0
CH_DEMO_DATA: 0
```

**Comment by iAMD1ver** [comment]
upvote issue. Will be nice to have instructions for how to save all of progress after stopping docker image.

**Comment by alex625051** [comment]
> upvote issue. Will be nice to have instructions for how to save all of progress after stopping docker image.

Hello! To save the data: 
I ran docker-compose according to the instructions from this repository. Then I stopped it with the `docker compose down` command. Then I changed the `docker-compose.yml` file: I found the `PG_TEST_DATA: 1` and
`CH_DEMO_DATA: 1` and replaced their values with `PG_TEST_DATA: 1`
`CH_DEMO_DATA: 1`. Then ran the command `docker compose up -d`

**Comment by JohnyDeath** [comment]
Предлагаемое здесь решение с "PG_TEST_DATA" и "CH_DEMO_DATA", насколько я понимаю, отключит демо-данные и демо-чарты.
Но хотелось бы, чтобы они оставались рядом с основными данным. Там много интересного и полезного можно почерпнуть.

**Comment by resure** [comment]
We have released updated version of metadata storage container and compose configuration. All configs are now persistent by default and you can also provide environment variable (`METADATA_POSTGRES_DSN_LIST`) for using external postgres database. More info in [readme](https://github.com/datalens-tech/datalens#running-containers).

(one possible caveat with `METADATA_POSTGRES_DSN_LIST`: if you want to pass local postgres dsn, you probably should use `host.docker.internal` instead of `localhost`, we'll add this to FAQ).

**Comment by Vaadimm** [comment]
Кто же по умолчанию прописывает такие параметры в compose. 
Потеряли наработки за неделю.

**Comment by resure** [comment]
Closing this issue since all metadata is now persistent by default.
