### ISSUE TITLE
navigation error when editing a chart

### ISSUE THREAD

**Issue by handgunman** [datalens-tech/datalens#194]
Hello!

When I select edit chart on the dashboard, the new tab does not open the chart in edit mode, but the section of workbooks.

[v1.11.0]

Cheers!

**Comment by Marginy605** [comment]
@handgunman Hi, I can't reproduce problem on release v1.11.0. Could you give more details: every step to reproduce this case.

**Comment by handgunman** [comment]
step by step:

1. open dashboard 
2. select "..." and edit
3. opened new tab "collections"

**Comment by handgunman** [comment]
The Zitadel is on the case, probably

**Comment by imsitnikov** [comment]
@handgunman hi! This bug is fixed in the latest release – [v1.11.1](https://github.com/datalens-tech/datalens/releases/tag/v1.11.1)

Thx for reporting!
