### ISSUE TITLE
Datalens with Zitadel perfomance issue

### ISSUE THREAD

**Issue by nasonovsm** [datalens-tech/datalens#198]
## Expected Behavior

Without the Zitadel service, dashboards are loaded within a few seconds (1-5 seconds for each chart) on the same VM

## Current Behavior

After Datalens with Zitadel  test deployment I observe high CPU consumption by zitadel and zitadel-db services and long load time of each chart.
At datalens.yandex.cloud:
<img width="703" alt="image" src="https://github.com/user-attachments/assets/6d841872-1ac8-43e6-8179-7fc92fc3c59b">

The same chart on the same dashboard at the Datalens Opensource:
<img width="628" alt="image" src="https://github.com/user-attachments/assets/1bb1de79-2d53-42cb-a3b2-215640a3c64c">

At the same dashboard without Zitadel service:
![telegram-cloud-photo-size-2-5413376471097008137-y](https://github.com/user-attachments/assets/2b7b0dc4-e0c5-4fe7-94f1-b4707ab3d355)

Docker stats command output:
<img width="844" alt="image" src="https://github.com/user-attachments/assets/d7592991-7aab-4d11-bace-468118cac693">

CPU grafana chart:
![telegram-cloud-photo-size-2-5413376471097008139-y](https://github.com/user-attachments/assets/577969ab-eab1-4376-8b3e-6fc5e34b89c9)

In logs of zitadel-db container with enabled debug mode I observe thousands SELECT and INSERT queries when accessing the dashboard. For example:

```sql
LOG:  execute stmtcache_675670f51ec7e588ce13abe2034bee6e90eafcd0d9907150: SELECT created_at, event_type, "sequence", "position", payload, creator, "owner", instance_id, aggregate_type, aggregate_id, revision FROM eventstore.events2 WHERE instance_id = $1 AND ((aggregate_type = $2 AND event_type = $3) OR (aggregate_type = $4 AND event_type = ANY($5)) OR (aggregate_type = $6 AND event_type = ANY($7)) OR (aggregate_type = $8 AND event_type = $9)) AND "position" > $10 AND "position" < (SELECT COALESCE(EXTRACT(EPOCH FROM min(xact_start)), EXTRACT(EPOCH FROM now())) FROM pg_stat_activity WHERE datname = current_database() AND application_name = 'zitadel_es_pusher' AND state <> 'idle') ORDER BY "position", in_tx_order LIMIT $11 OFFSET $12

LOG:  execute stmtcache_a614765bc81cd263e6301614a7396ccd287ac629e218f5ed: INSERT INTO projections.current_states (
	    projection_name
	    , instance_id
	    , aggregate_id
	    , aggregate_type
	    , "sequence"
	    , event_date
	    , "position"
	    , last_updated
	    , filter_offset
	) VALUES (
	    $1
	    , $2
	    , $3
	    , $4
	    , $5
	    , $6
	    , $7
	    , now()
	    , $8
	) ON CONFLICT (
	    projection_name
	    , instance_id
	) DO UPDATE SET
	    aggregate_id = $3
	    , aggregate_type = $4
	    , "sequence" = $5
	    , event_date = $6
	    , "position" = $7
	    , last_updated = statement_timestamp()
	    , filter_offset = $8
	;
```

## Environment

All docker containers runs on Yandex Compute Cloud VM (2 vCPU, 4 GB RAM, SSD) and Datalens (Cloud and Opensource ) connected to Managed service for Clickhouse database.

Docker images versions:
```env
DL_CONTROL_API_VERSION=0.2139.0
DL_DATA_API_VERSION=0.2139.0
DL_US_VERSION=0.239.0
DL_UI_VERSION=0.2000.0
DL_ZITADEL_VERSION=2.61.0
```

OS version:
```env
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```
Docker version:
```
Server: Docker Engine - Community
 Engine:
  Version:          27.1.0
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       a21b1a2
  Built:            Fri Jul 19 17:42:53 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Is this the expected behavior of the zitadel and zitadel-db service?

**Comment by MaksSharkov** [comment]
I have exactly the same problem. I set up Zitadel as described in the Readme and launched DataLens.

When opening the Demo dashboard, all graphs load in 2-3 seconds. At the same time, there is a huge load on the server CPU. I even allocated 8 cores, but this did not improve the situation.
![image](https://github.com/user-attachments/assets/09277e91-0e79-47d4-8f66-0dfb071a897e)

The processes are sorted by CPU usage.

In the browser's DEV console, this picture is observed. The fastest requests take about 1.75 seconds, and the longest take 3.5 seconds.
![image](https://github.com/user-attachments/assets/c89a249f-f102-4fac-b981-a37ca44de62e)

I also looked at the logs of the Zitadel Docker container.
At the moment of loading dashboards, a huge number of the following messages fall into the Zitadel log.
```
time="2024-11-01T08:24:15Z" level=info msg="eventstore push retry" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/eventstore.go:104" error="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)"
time="2024-11-01T08:24:15Z" level=warning msg="could not push event \"project.application.oidc.secret.check.succeeded\"" caller="/home/runner/work/zitadel/zitadel/internal/command/command.go:305" error="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)"
time="2024-11-01T08:24:15Z" level=info msg="eventstore push retry" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/eventstore.go:104" error="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)"
time="2024-11-01T08:24:15Z" level=info msg="eventstore push retry" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/eventstore.go:104" error="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)"
time="2024-11-01T08:24:15Z" level=info msg="eventstore push retry" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/eventstore.go:104" error="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)"
time="2024-11-01T08:24:15Z" level=warning msg="could not push event \"project.application.oidc.secret.check.succeeded\"" caller="/home/runner/work/zitadel/zitadel/internal/command/command.go:305" error="ERROR: duplicate key value violates unique constraint \"events2_pkey\" (SQLSTATE 23505)"
```
