### ISSUE TITLE
Column chart проблем с отображением отрицательных значений по Y

### ISSUE THREAD

**Issue by arrowcircle** [datalens-tech/datalens#233]
Привет! Столкнулся с проблемой кривого отображения column chart - не отображается сетка для отрицательных значений по вертикальной оси.

- `HC=0`
- Последняя релизная версия v1.14 (на 1.13 проблема остается)
- График и данные ниже
- С line chart таких проблем нет

![chart](https://github.com/user-attachments/assets/885ee180-ca4e-4433-af90-b8aa624b1441)
![table](https://github.com/user-attachments/assets/9fb8d2df-02a5-4839-8c20-9cecee63356b)

**Comment by kuzmadom** [comment]
Available in [release v1.18.0](https://github.com/datalens-tech/datalens/releases/tag/v1.18.0)
