### ISSUE TITLE
Некорректный расчет высоты dashkit-grid-item для таблиц с автоматическим расчетом высоты

### ISSUE THREAD

**Issue by Kaonashi76** [datalens-tech/datalens#242]
Доброго времени суток. На тестовых и продовских дашбордах заметил, что высота dashkit-grid-item высчитывается не правильно. Ожидается, что высота контейнера подстроиться под размер таблицы + padding контейнера + высота шапки, но высота контейнера значительно выше. Так и задумывалось или все же это баг?
 
![image](https://github.com/user-attachments/assets/34c3939d-8840-4ca1-a426-6a662b2939c4)
![image](https://github.com/user-attachments/assets/e14c6828-cc07-4eb8-9725-dc6912752c0c)

**Comment by Marginy605** [comment]
@Kaonashi76 добрый день, подскажите, пожалуйста, в какой версии [opensource релиза](https://github.com/datalens-tech/datalens/releases) это воспроизводится? Пробовали обновиться на самую свежую версию? 

P.S. на всякий случай поясню, что здесь не ведется поддержка для облачной и enterprise версий DataLens, чтобы получить консультацию по работе интерфейса в этих инсталляциях, обратитесь в соответствующие каналы поддержки

**Comment by Kaonashi76** [comment]
После обновления до самой свежей версии, проблема, вроде, разрешилась, спасибо!
