### ISSUE TITLE
Не подгружаются дашборды, графики и новое подключение

### ISSUE THREAD

**Issue by MaxanKRD** [datalens-tech/datalens#251]
Всем добрый день! Подняли VM под datalens в закрытой среде организации.
По адресу уходим на web-морду datalens - но она пустая, нет графиков, дашбордов, не можем создать новое подключение. Буду благодарен за помощь в данном вопросе.
![12](https://github.com/user-attachments/assets/64b1d230-bf00-4657-9b9e-9992436134aa)
[control-api.txt](https://github.com/user-attachments/files/17974912/control-api.txt)
[data-api.txt](https://github.com/user-attachments/files/17974913/data-api.txt)
[datalens-ui.txt](https://github.com/user-attachments/files/17974914/datalens-ui.txt)
[datalens-us.txt](https://github.com/user-attachments/files/17974915/datalens-us.txt)

**Comment by goshander** [comment]
@MaxanKRD привет, можете пожалуйста уточнить список запущенных контейнеров через команду
`docker ps`

На основе какого docker-compose файла выполнялось разверытвание?

**Comment by MaxanKRD** [comment]
[docker-compose.txt](https://github.com/user-attachments/files/17981287/docker-compose.txt)

**Comment by MaxanKRD** [comment]
c02a20c62464   control-api:api        "/etc/service/dl_api…"   6 minutes ago   Up 6 minutes    8080/tcp                                datalens-control-api
bee904684bc1   data-api:api           "/etc/service/dl_api…"   6 minutes ago   Up 6 minutes    8080/tcp                                datalens-data-api
5d49d3d1800a   ui-datalens:latest     "/usr/bin/supervisor…"   14 hours ago    Up 10 minutes   0.0.0.0:80->8080/tcp, :::80->8080/tcp   datalens-ui
0fb6323c9184   datalens-usv2:latest   "/usr/bin/supervisor…"   14 hours ago    Up 10 minutes                                           datalens-us
6cf1735ba4ea   postgres13:alpine      "docker-entrypoint.s…"   16 hours ago    Up 10 minutes   5432/tcp                                datalens-pg-demo-connection
23db0228aa7c   postgres13:alpine      "docker-entrypoint.s…"   16 hours ago    Up 10 minutes   5432/tcp                                datalens-pg-us
37dddbe10d74   postgres13:alpine      "docker-entrypoint.s…"   16 hours ago    Up 10 minutes   5432/tcp                                datalens-pg-compeng

У меня запустился datalens-control-api ( была отключена служба ipv6) - в логах была ошибка по этому поводу. Но, ситуация не изменилась. так же в контейнере datalens-control-api такая ошибка: "name": "gunicorn.error", "levelname": "INFO", "exc_info": null, "lineno": 278, "funcName": "info", "timestamp"

**Comment by MaxanKRD** [comment]
Вроде бы разобрался, подключения появились.
Но в demo-режиме:
![image](https://github.com/user-attachments/assets/7dca52ec-5d52-485c-9de2-1e255f461410)

Хотя подключение к pg-demo-connection

**Comment by goshander** [comment]
Подскажите пожалуйста, вы используете какую-то кастомную сборку контейнеров для развёртывания?

**Comment by MaxanKRD** [comment]
нет, те же, что и были указаны в вашем docker-compose. Нам эти контейнеры после проверки безопасности затянули в наш локальный харбор, а оттуда я забрал в нашу VM - на ней нет интернета

**Comment by MaxanKRD** [comment]
Извиняюсь, я разобрался с ошибками. проблема была в портах. Все заработало.
