### ISSUE TITLE
Datalens не дает создать комбинированный чарт

### ISSUE THREAD

**Issue by davynchi** [datalens-tech/datalens#253]
Здравствуйте.
Рзавернут Datalens на Kubernetes, версия 1.16.0. Пытаюсь создать комбинированный чарт. Следую [документации](https://datalens.tech/docs/ru/visualization-ref/combined-chart.html). Не могу выполнить шаг 5 (Выберите тип чарта Комбинированная диаграмма.), так как кнопки выбора комбинированной диаграммы нет. Пробовал на разных датасетах, нет ни для одного. При этом выставлен HC=1.
![photo_2024-12-03_10-23-15](https://github.com/user-attachments/assets/10be26cb-c599-4476-bc32-505d5787988d)

Подскажите, пожалуйста, в чем может быть проблема и как ее решить?

**Comment by goshander** [comment]
@davynchi привет, подскажите пожалуйста вы использовали для развертывания helm чарты?
Параметр HC=1 должен быть указан и для UI и для US контейнера

**Comment by davynchi** [comment]
Добрый день. Извините за долгий ответ.
Уже пофиксили проблему, прописали HC: ${HC:~1} в docker-compose.yml и docker-compose-dev.yml
Но все равно спасибо за Ваш отклик.
