### ISSUE TITLE
datalens: correct nginx proxy

### ISSUE THREAD

**Issue by phoedos** [datalens-tech/datalens#259]
Please guide me for proper proxying datalens via nginx: 
**datalens.conf**
```
server {
listen 80;
server_name datalens;
root /opt/datalens/;
    location / {
        proxy_set_header  Host              $host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_set_header  X-Forwarded-Proto $scheme;
       #to docker listen port
        proxy_pass        http://127.0.0.1:8080;
        proxy_read_timeout  600;
        proxy_redirect off;
    }
}
```
and as a result face with:
```
[error] 13002#13002: *25 open() "/opt/datalens/build/js/dl-main.98e55631.js" failed (2: No such file or directory), client: xxxxx, server: datalens, request: "GET /build/js/dl-main.98e55631.js HTTP/2.0", host: "datalens", referrer: "http://datalens/"
<and so on...>
```

the issue resolved only after copying sources from docker container to host 
```
docker cp  datalens-ui:/opt/app/dist/public/build /opt/datalens/
```

is it possbile giide how correctly proxy app ?

**Comment by goshander** [comment]
@phoedos hi, could you describe your case in more detail?
Why do I need an additional nginx over ui container?

**Comment by phoedos** [comment]
dear @goshander  
need to present project as experimental dashboard to my collegues inside corporate network with using self-signed ssl certificates.
Thus either I edit manually configs in dockerized UI or I setup standalone nginx and just proxy_path requests to dockerized ui:8080. 
This is a regular practice to share dockerized projects via nginx.

**Comment by phoedos** [comment]
sorry guys, my bad, wrong nginx configuration. 
proxy_pass is working fine now, no additional changes required.
