### ISSUE TITLE
Non clear error messages

### ISSUE THREAD

**Issue by diggerburg** [datalens-tech/datalens#27]
Hi there!
Are there any docs (besides those that are in Yandex.Cloud docs) covering the creation of datasets and possible error codes? I'm trying to create a dataset with an SQL query for a connected Postgres connection, but I'm stuck with this:

```
Relation requires at least one condition
ERR.DS_API.FORMULA
{
    "title": "ERR.DS_API.FORMULA",
    "description": "Relation requires at least one condition"
}
```

```
ERR.DS_API.VALIDATION.ERROR
[
    {
        "id": "340a4261-635d-11ee-85cb-db624a6af76d",
        "type": "avatar_relation",
        "errors": [
            {
                "level": "error",
                "code": "ERR.DS_API",
                "message": "Relation requires at least one condition",
                "details": {}
            }
        ]
    }
]
```

Unfortunately, nothing was found on the Internet, except [this](https://cloud.yandex.com/en/docs/datalens/troubleshooting/errors/all) page, but it doesn't help :(

The query works independently and it has conditions.

Thanks!

**Comment by paveldubinin** [comment]
Here is documentation for Open Source Project https://datalens.tech/docs/en/troubleshooting/errors/all.html . But for now its very similar to Cloud.

Regarding your error. What kind of SQL are you using? Could you please also provide screenshot of dataset UI?

**Comment by diggerburg** [comment]
Hey Pavel,
Thanks for the link! Disregard my error, please; the reason was that I added both aggregated and non-aggregated datasets and messed up the tables. Thanks to all the Arkadies for open-sourcing DataLens!
