### ISSUE TITLE
No user privilege settings

### ISSUE THREAD

**Issue by whoandwhere** [datalens-tech/datalens#28]
Will it be added in the future?

**Comment by resure** [comment]
Yes, basic auth & ACLs would be definetely added in the future.

**Comment by vialex28** [comment]
What about OAuth2/OIDC?

**Comment by zagorulkinde** [comment]
Do you have some roadmap? How to upvote for feature requests?

**Comment by resure** [comment]
We will post roadmap later, but without a doubt this is one of the most requested features.

**Comment by indigoram89** [comment]
+

**Comment by resure** [comment]
This is planned: https://github.com/datalens-tech/datalens/issues/100
You can subscribe to that issue and be notified when ACL would be released.
