### ISSUE TITLE
Сould not open certificate file (PostgreSQL)

### ISSUE THREAD

**Issue by stpnvkirill** [datalens-tech/datalens#32]
When connecting to Yandex Cloud Managed Service for PostgreSQL, it gives error. DataLens is deployed locally, loading a certificate file via Advanced connection settings does not help. 

Through dbeaver I can connect to the database from this machine.

OS: Linux version 6.2.0-34-generic (buildd@lcy02-amd64-025) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.40)
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

Error text: 
`Database error.
ERR.DS_API.DB
{
    { "data": {
        { "code": "ERR.DS_API.DB",
        "details": {
            "db_message": "connection to server at "..." (...), port 6432 failed: could not open certificate file \"/root/.postgresql/postgresql.crt\": Permission denied\n""
        },
        "message": "Database error."
        "debug": {
            "db_message": "connection to server at "..." (...), port 6432 failed: could not open certificate file \"/root/.postgresql/postgresql.crt\": Permission denied\n".
            "query": "select 1"
        }
    }
}`

**Comment by resure** [comment]
Just to be clear: have you tried adding additional root certificate as described in FAQ?



> #### How can I specify custom certificate for connecting to metadata database?
> You can add additional certificates to the database in `./certs/root.crt`, they will be used to connect to the database from the datalens-us container.
