### ISSUE TITLE
Ошибка после установки (Error after instalation)

### ISSUE THREAD

**Issue by drpavlic** [datalens-tech/datalens#38]
Привет.
После установки ошибка.
Нет коллекций и воркбуков.
----------------------
ECONNABORTED
{
    "title": "Ошибка",
    "description": "Превышено время ожидания ответа"
}

![изображение](https://github.com/datalens-tech/datalens/assets/17545919/876d801e-6ed0-4214-bac9-9c373154598c)

------------------
[paulmer@docker-01 ~]$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="38 (Thirty Eight)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
[paulmer@docker-01 ~]$

**Comment by resure** [comment]
Do you run compose from cloned repository, or just copied `docker-compose.yml`?

**Comment by belonesox** [comment]
Did you use docker from moby package, or docker from podman emulation?
check it if «rpm -qa | grep docker» → podman-docker → then you have podman emulation

Running DL on FC37 and FC38 with podman-docker I have to make some changes to run DL.
