### ISSUE TITLE
Broken demo «Интерактивный пример встроенного чарта» in a documentation post

### ISSUE THREAD

**Issue by belonesox** [datalens-tech/datalens#42]
Broken demo «Интерактивный пример встроенного чарта» in a documentation post

https://cloud.yandex.ru/blog/posts/2021/06/datalens-digest-june-2021

![image](https://github.com/datalens-tech/datalens/assets/1609739/c6315b4c-5e6b-41a2-841d-3b4787de7e3d)

**Comment by paveldubinin** [comment]
fixed!
