### ISSUE TITLE
Нет возможности добавить линейный диаграмму

### ISSUE THREAD

**Issue by ilya120794** [datalens-tech/datalens#45]
Добрый день! Пытаюсь построить линейную диаграмму в DataLens: при выборе графика - такого нет. Прикладываю скрин экрана:
![image](https://github.com/datalens-tech/datalens/assets/150899262/3c6e2327-ac87-4f93-ad8e-c6ad42a6fb89)

Захожу сюда: 
![image](https://github.com/datalens-tech/datalens/assets/150899262/7069cc5b-ec9d-4e2e-8ee8-9f23f65f50c6)

У меня ошибка:
![image](https://github.com/datalens-tech/datalens/assets/150899262/925e6c1d-17d6-4f01-95d6-e0828438d2fe)

Подскажите, может я что то делаю не то.

**Comment by resure** [comment]
Do you start datalens with highcharts enabled? `HC=1` option

**Comment by ilya120794** [comment]
DataLens was launched without HC = 1

**Comment by ilya120794** [comment]
@resure thenks you for your help. launched with HC = 1 and it resolved the problems
