### ISSUE TITLE
Ports are not available: exposing port TCP 0.0.0.0:50500 

### ISSUE THREAD

**Issue by ssharapov** [datalens-tech/datalens#48]
After [Windows 10 Update KB4074588](https://support.microsoft.com/en-us/help/4074588/windows-10-update-kb4074588), some ports are reserved by Windows and applications cannot bind to these ports. 50500 is in the blocked range.

You can use netsh interface ipv4 show excludedportrange protocol=tcp to list the reserved ranges.

![image](https://github.com/datalens-tech/datalens/assets/77724577/9c4e5314-8106-4007-b2c2-51c879bf5349)

**Comment by resure** [comment]
@imsitnikov can you please take a look? We're currently using port 50500 for united-storage, but can probably switch it to some other port.

**Comment by imsitnikov** [comment]
> @imsitnikov can you please take a look? We're currently using port 50500 for united-storage, but can probably switch it to some other port.

PR with 8083 port for united-storage – https://github.com/datalens-tech/datalens/pull/55

**Comment by imsitnikov** [comment]
> PR with 8083 port for united-storage – #55

Merged.

@ssharapov you can pull the `main` branch and this problem will be solved.
