### ISSUE TITLE
Add MSSQL connector

### ISSUE THREAD

**Issue by andrejs82git** [datalens-tech/datalens#5]
Hello!

Please give info how to add mssql connection.

Thanks!

**Comment by Konstantin-Roumas** [comment]
https://cloud.yandex.com/en/docs/datalens/operations/connection/create-mssql-server

**Comment by resure** [comment]
> Please give info how to add mssql connection.

We are going to add this connector little later. Can't say exactly when, but we'll soon publish roadmap.
