### ISSUE TITLE
Cannot connect to metadata PostgreSQL with TLS/SSL

### ISSUE THREAD

**Issue by pashkov-v** [datalens-tech/datalens#53]
When trying to connect to metadata PostgreSQL DB with TLS/SSL, the following error appears when running `scripts/preflight.sh` (I was trying to connect to Yandex Managed Service for PostgreSQL):

```error: odyssey: c3577ff1eb926: SSL is required```

Although the correct root certificate is present in `/certs/root.crt`, it does not help.

It seems like [here](https://github.com/datalens-tech/datalens-us/blob/087d4f7531521a3eea497da4c07f8524ec0abdd4/src/db/init-db.ts#L92C5-L92C5) certificate path is not passed to `initPosgresDB()` (although I could not find the signature of this function since `gravity-ui/postgreskit` is probably a private repo).

The solution that worked for me was to add the following parameters to DSN:
`postgres://{user}:{password}@{host}:{port}/{database}?sslmode=verify-full&sslrootcert=/certs/root.crt`.

I think that this solution may be added to README.

**Comment by resure** [comment]
>  (although I could not find the signature of this function since gravity-ui/postgreskit is probably a private repo).

it's public: https://github.com/gravity-ui/postgreskit
