### ISSUE TITLE
How to enable export to excel ? 

### ISSUE THREAD

**Issue by overpod** [datalens-tech/datalens#54]
We are ready to test your product. Our analysts noticed that there is no possibility of uploading to Excel. How to fix it ?

**Comment by overpod** [comment]
We use metabase, this feature is there!!!

**Comment by melikhov-dev** [comment]
Hi @overpod! Yes, we have disabled this feature for the open source version. We need to refactor this feature, hopefully it will be done soon. I'm working on this right now.

**Comment by overpod** [comment]
Great news. I'm waiting for the release of this feature
