### ISSUE TITLE
`docker-compose` instead of `docker compose`?

### ISSUE THREAD

**Issue by alexey-milovidov** [datalens-tech/datalens#6]
I'm following the readme on the Ubuntu machine, and for some reason, I have to type `docker-compose` instead of `docker compose`.

**Comment by Konstantin-Roumas** [comment]
Do you have **docker-compose** and **docker compose** on your pc?

**Comment by dishkakrauch** [comment]
Please provide you docker engine version and docker compose version.

**Comment by alexey-milovidov** [comment]
```
$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
$ docker-compose --version
docker-compose version 1.29.2, build unknown
```

**Comment by alexey-milovidov** [comment]
I have only `docker-compose`, the `docker compose` shows

```
$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Comment by Konstantin-Roumas** [comment]
> I have only `docker-compose`, the `docker compose` shows
> 
> ```
> $ docker compose
> docker: 'compose' is not a docker command.
> See 'docker --help'
> ```

So that's why you should type docker-compose, cause you havn't got `docker compose` in your system

**Comment by alexey-milovidov** [comment]
Yes, I understand. I was following the README, but copy-pasting the commands from the README didn't work.
It means that the README is incorrect. The step-by-step instructions should be accessible to an unsophisticated user.

**Comment by Konstantin-Roumas** [comment]
> Yes, I understand. I was following the README, but copy-pasting the commands from the README didn't work.
> It means that the README is incorrect. The step-by-step instructions should be accessible to an unsophisticated user.

Are you checked link to docker wiki how to install docker?

**Comment by alexey-milovidov** [comment]
I did it a long time ago and don't remember how.

**Comment by alexey-milovidov** [comment]
I just wanted to highlight that the usability is not 100% flawless.

**Comment by alexey-milovidov** [comment]
By the way, the first open of Datalens briefly shows some error, but then it disappears and doesn't show again.
