### ISSUE TITLE
Slight markup error in "create chart"

### ISSUE THREAD

**Issue by alexey-milovidov** [datalens-tech/datalens#7]
![Screenshot_20230926_184521](https://github.com/datalens-tech/datalens/assets/18581488/18560fba-1954-4ff3-85fa-d6a56f165dfc)

The bottom border of an input field does not show.

**Comment by resure** [comment]
Trying to reproduce this. What browser do you use? And by any chance have you viewed this page while zoomed in in your browser (ctrl/cmd+)?

**Comment by alexey-milovidov** [comment]
Firefox with 150% zoom.

**Comment by korvin89** [comment]
@alexey-milovidov Hey! Could you check this issue one more time? We have refactored this  part of UI not so long ago. I can't reproduce this bug now

**Comment by korvin89** [comment]
We have reworked this part of UI. If you will reproduced problem please reopen this issue
