### ISSUE TITLE
When I click at ? icon, the help quickly appears and disappears

### ISSUE THREAD

**Issue by alexey-milovidov** [datalens-tech/datalens#9]
![Screenshot_20230926_184928](https://github.com/datalens-tech/datalens/assets/18581488/d34c22ae-08ef-448c-8977-70f6c553643e)

Steps to reproduce: move the mouse pointer to the `?` icon and click on it quickly.

**Comment by resure** [comment]
Yeah, it currently only works with hovers, not with clicks. That can be pretty annoying, we probably should just support both hovers and clicks.

**Comment by korvin89** [comment]
Will be fixed in https://github.com/gravity-ui/uikit/issues/1083
