### ISSUE TITLE
Markup improvements

### ISSUE THREAD

**Issue by Marginy605** [datalens-tech/datalens#92]
Add markup functions for text formatting: color, size and text wrapping. 
Add markup functions for displaying images.

In the first iteration, this should work in tables and indicators.

**Comment by artemipanchuk** [comment]
https://github.com/datalens-tech/datalens-ui/pull/538

https://github.com/datalens-tech/datalens-ui/pull/556

https://github.com/datalens-tech/datalens-ui/pull/606

https://github.com/datalens-tech/datalens-ui/pull/629

https://github.com/datalens-tech/datalens-ui/pull/631

https://github.com/datalens-tech/datalens-ui/pull/633

https://github.com/datalens-tech/datalens-ui/pull/686
